@startuml

database "SRAM-LDAP" {
  [Service Data]
}

package [CBA] {
  [SCIM Client]
}

package [SCIM-Service] {
  [SCIM Server]
  [Cronjob]

  database "MongoDB" {
    [SCIM Data]
  }
}

[Cronjob] <-- [Service Data]: Read / Only
[Cronjob] <--> [SCIM Server]: Read / Write
[SCIM Server] <-> [SCIM Data]
[SCIM Client] --> [SCIM Server] : Get Users / Groups
@enduml